### ISSUE TITLE
Search words

### ISSUE THREAD

**Issue by BenTBCampbell** [BenTBCampbell/Software-Engineering#25]
- [x] Add a search bar to the main page
- [x] Have a search page
- [x] Improve UI on search page

**Comment by BenTBCampbell** [comment]
At this point we have the UI and code to query the database. We just need to connect the UI to that code, which I'm working on this week.

**Comment by BenTBCampbell** [comment]
Now the search page works, but it doesn't look very pretty. Maybe @usa4cc or @BattierFuego can work on making it look better.

**Comment by BenTBCampbell** [comment]
Also, we dont' have a good way to handle just displaying all words. I just made it do that if you search *

**Comment by BenTBCampbell** [comment]
Chris showed me how to implement the search bar on the home page, so now everything works, we just need to make it look nicer.

**Comment by BattierFuego** [comment]
Alright, I couldn't really add too much detail to a drawing, but here is something
https://photos.app.goo.gl/TVfMkdcCnp1C3HmE9

**Comment by BenTBCampbell** [comment]
Alright, search bar is implemented! There's a few improvements that could be made, but that's for another issue.
