### ISSUE TITLE
Move release from the wiki to a Github tag

### ISSUE THREAD

**Issue by 2br-2b** [BenTBCampbell/Software-Engineering#9]
Right now, you have your project in the wiki. Instead, these should be tags and/or releases on Github. This lets you keep track of what commits were made at the point you compile the apk, and what commits have been made since the release. It's also common practice on Github.

See https://www.toolsqa.com/git/github-tags/ and https://www.toolsqa.com/git/github-releases/ for more info on this.

**Comment by BenTBCampbell** [comment]
Thanks John! We didn't know about releases, but it was pretty quick to make, so I just did it. I think I'll leave the wiki up as well for the non tech-saavy users.
